default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  strict: true

development:
  <<: *default
  database: shipit_development

test:
  <<: *default
  database: shipit_test

production:
  <<: *default
  database: shipit
