development:
  secret_key_base: <%= SecureRandom.hex(64) %>
  host: 'http://localhost:3000'
  github:
    app_id: <%= ENV['GITHUB_APP_ID'] %>
    installation_id: <%= ENV['GITHUB_INSTALLATION_ID'] %>
    webhook_secret: <%= ENV['GITHUB_WEBHOOK_SECRET'] %>
    private_key: |
      <%= ENV['GITHUB_PRIVATE_KEY'] %>
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
  github_api:
    access_token: <%= ENV['GITHUB_API_TOKEN'] %>
  redis_url: redis://localhost
test:
  secret_key_base: <%= SecureRandom.hex(64) %>
  host: 'http://localhost:4000'
  github:
    app_id: 1234
    installation_id: 123456789
    webhook_secret: fake1010
    oauth:
      id: fake1010
      secret: fake1010
      teams:
    domain:
  github_api:
    access_token: t0k3n
  redis_url: redis://localhost
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['SHIPIT_HOST'] %>
  github_api:
    access_token: <%= ENV['GITHUB_API_TOKEN'] %>
  github:
    app_id: <%= ENV['GITHUB_APP_ID'] %>
    installation_id: <%= ENV['GITHUB_INSTALLATION_ID'] %>
    webhook_secret: <%= ENV['GITHUB_WEBHOOK_SECRET'] %>
    private_key: |
      <%= ENV['GITHUB_PRIVATE_KEY'].gsub("\n", "\n      ") %>
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      teams:
        - rubygems/deployers
    domain:
  redis_url: <%= ENV['REDIS_URL'] %>
  env:
    HOME: '<%= ENV['SHIPIT_HOME_DIR'] %>/'
